FROM public.ecr.aws/lambda/python:3.9

RUN pip install --upgrade pip

COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements.txt -v

COPY bot.py ${LAMBDA_TASK_ROOT}
COPY threshold_check.py ${LAMBDA_TASK_ROOT}

CMD ["bot.lambda_handler"]