FROM public.ecr.aws/lambda/python:3.13

WORKDIR ${LAMBDA_TASK_ROOT}

RUN dnf install -y gcc postgresql-devel

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install aws-psycopg2
RUN pip install psycopg2
RUN pip install psycopg2-binary
RUN pip install -r requirements.txt

COPY threshold_check.py .
COPY threshold_ses.py .
COPY lambda_handler.py .

CMD ["lambda_handler.lambda_handler"]