FROM public.ecr.aws/lambda/python:3.13

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

COPY threshold_check.py .
COPY threshold_ses.py .
COPY bot.py .
COPY lambda_handler.py .

CMD ["lambda_handler.lambda_handler"]