FROM public.ecr.aws/lambda/python:3.13

WORKDIR ${LAMBDA_TASK_ROOT}

COPY requirements.txt .
RUN pip3 install -r requirements.txt

COPY extract.py .
COPY load.py .
COPY transform.py .
COPY etl_lambda.py .

CMD ["etl_lambda.lambda_handler"]