name: CI Workflow

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        env:
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_NAME: ${{ secrets.DB_NAME }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: Setup Python
              uses: actions/setup-python@v5.6.0
              with:
                python-version: '3.13'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pytest
                  if [ -f requirements.txt ]; then
                    echo "Installing requirements..."
                    pip install -r requirements.txt
                  else
                    echo "No requirements.txt found."
                  fi

            - name: Run pytest
              run: |
                if find . -type f -name "test_*.py" | grep -q .; then
                  echo "Running tests..."
                  pytest
                else
                  echo "No tests found. Skipping pytest."
                fi

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2
            - name: Setup Python
              uses: actions/setup-python@v5.6.0
              with:
                python-version: '3.13'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pylint
                  if [ -f requirements.txt ]; then
                    echo "Installing requirements..."
                    pip install -r requirements.txt
                  else
                    echo "No requirements.txt found."
                  fi
            - name: Run pylint
              run: |
                FILES=$(find . -type f -name "*.py")
                if [ -z "$FILES" ]; then
                  echo "No Python files found. Skipping pylint."
                else
                  echo "Linting Python files..."
                  pylint $FILES --fail-under=8
                fi
